apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - api.yaml
  - admin.yaml
  - sync-cronjob.yaml
  - cloudflared.yaml
  - pdb.yaml
