apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudflared-pdb
  namespace: causas
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: causas
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/part-of: causas
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-pdb
  namespace: causas
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: causas
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/part-of: causas
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: admin-pdb
  namespace: causas
  labels:
    app.kubernetes.io/name: admin
    app.kubernetes.io/part-of: causas
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: admin
      app.kubernetes.io/part-of: causas
